services:
  qiita-db:
    image: postgres:15
    container_name: qiita-db
    hostname: qiita-db
    network_mode: host
    restart: no
    env_file:
      - ./environments/qiita_db.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_DB_USER=postgres
    volumes:
      - './environments/qiita-db-init.sh:/docker-entrypoint-initdb.d/qiita-db-init.sh'
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - "6543:5432"

  qiita:
      image: qiita:latest 
      command: ['./start_qiita.sh'] #executes bash script inside the container
      stdin_open: true
      tty: true
      network_mode: host
      ports:
        - "21174:21174"  #wihtout nginx
      restart: no
      depends_on:
        - qiita-db
      env_file:
        - './environments/qiita.env'
      environment:
        - QIITA_ROOTCA_CERT=/qiita/qiita_core/support_files/ci_rootca.crt
        - QIITA_CONFIG_FP=/qiita/qiita_core/support_files/config_test.cfg


volumes:
  postgres-data:
    name: qiita-postgres-data
