services:
  qiita-db:
    image: postgres:15
    container_name: qiita-db
    hostname: qiita-db
    restart: no
    env_file:
      - ./environments/qiita_db.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - './environments/qiita-db-init.sh:/docker-entrypoint-initdb.d/qiita-db-init.sh'
      - 'postgres-data:/var/lib/postgresql/data'
      - server-plugin-configs:/qiita_plugins
    networks:
      - qiita-net
    ports:
      - "15432:5432"

  qiita:
      image: local-qiita:latest
      build: # image wird hier direkt gebaut
        context: ./Images/qiita
        dockerfile: Dockerfile
      command: ['/start_qiita.sh'] # executes bash script inside the container
      # entrypoint: /bin/bash
      # stdin_open: true
      # tty: true
      # ports:
        # - "21174:21174"  # wihtout nginx
        # - 127.0.0.1:8383:8383 #damit bur ich dran komme
      restart: no
      depends_on:
        - qiita-worker
      env_file:
        - './environments/qiita.env'
      environment:
        #- QIITA_ROOTCA_CERT=/qiita_certificates/stefan_rootca.crt  # does not seem to have effect if not set in config file
        - QIITA_CONFIG_FP=/qiita_configurations/qiita_server.cfg
        - PORT=21174
        - MASTER=--master
        - QIITA_CLIENT_DEBUG_LEVEL=DEBUG
      volumes:
        #- qiita-data:/qiita
        - ./src/qiita:/qiita:U
        - ./logs:/logs
        - ./Images/qiita/config_qiita_oidc.cfg:/qiita_configurations/qiita_server.cfg:r
        - server-plugin-configs:/qiita_plugins
        - server-certificates:/qiita_certificates
        # - ./Images/qiita/start_qiita.sh:/qiita/start_qiita.sh
      networks:
        - qiita-net
      ports:
      - "21174:21174"
    # deploy:
      #   replicas: 3
  qiita-worker:
      image: local-qiita:latest
      build: # image wird hier direkt gebaut
        context: ./Images/qiita
        dockerfile: Dockerfile
      command: ['./start_qiita.sh'] # executes bash script inside the container
      # entrypoint: /bin/bash
      # stdin_open: true
      # tty: true
      # ports:
        # - "21174:21174"  # wihtout nginx
        # - 127.0.0.1:8383:8383 #damit bur ich dran komme
      restart: no
      depends_on:
        - redis
        - plugin-collector
      env_file:
        - './environments/qiita.env'
      environment:
        #- QIITA_ROOTCA_CERT=/qiita_certificates/stefan_rootca.crt  # does not seem to have effect if not set in config file
        - QIITA_CONFIG_FP=/qiita_configurations/qiita_server.cfg
        - PORT=21175
        - MASTER=
        - QIITA_CLIENT_DEBUG_LEVEL=DEBUG
      volumes:
        - qiita-data:/qiita
        - ./logs:/logs
        - ./Images/qiita/config_qiita_oidc.cfg:/qiita_configurations/qiita_server.cfg:r
        - server-plugin-configs:/qiita_plugins
        - server-certificates:/qiita_certificates
        # - ./Images/qiita/start_qiita_worker.sh:/qiita/start_qiita_worker.sh
      networks:
        - qiita-net
      deploy:
        replicas: 3
  redis:
    image: redis:latest
    restart: no
    command: >
      sh -c "redis-server --port 7777 &&
             redis-server --port 6379"
    volumes:
      - qiita-data:/qiita
      - ./logs:/logs
    networks:
      - qiita-net
  #~ keycloak: # from https://stackoverflow.com/questions/78071458/keycloak-docker-compose
    #~ image: quay.io/keycloak/keycloak:24.0.2
    #~ container_name: keycloak
    #~ environment:
      #~ KC_DB: postgres
      #~ KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      #~ KC_DB_USERNAME: keycloak
      #~ KC_DB_PASSWORD: password

      #~ KC_HOSTNAME: keycloak
      #~ KC_HOSTNAME_PORT: 9999
      #~ KC_HOSTNAME_STRICT: false
      #~ KC_HOSTNAME_STRICT_HTTPS: false

      #~ KC_LOG_LEVEL: info
      #~ KC_METRICS_ENABLED: false
      #~ KC_HEALTH_ENABLED: true
      #~ KEYCLOAK_ADMIN: admin
      #~ KEYCLOAK_ADMIN_PASSWORD: admin
    #~ command: ["start-dev", "--http-port=9999"]
    #~ depends_on:
      #~ - keycloakdb
    #~ ports:
      #~ - 127.0.0.1:9999:9999
    #~ networks:
      #~ - qiita-net

  #~ keycloakdb:
    #~ image: postgres:15
    #~ volumes:
      #~ - keycloak-postgres-data:/var/lib/postgresql/data
    #~ environment:
      #~ POSTGRES_DB: keycloak
      #~ POSTGRES_USER: keycloak
      #~ POSTGRES_PASSWORD: password
    #~ networks:
      #~ - qiita-net

  nginx:
    image: local-nginx_qiita:latest
    build:
      context: ./Images/nginx
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
    command: ['./start_nginx.sh']
    # stdin_open: true
    # tty: true
    restart: no
    depends_on:
      - qiita
    volumes:
      - qiita-data:/qiita
      #- ./logs/nginx_access.log:/logs/nginx_access.log
      #- ./logs/nginx_error.log:/logs/nginx_error.log
      - ./logs:/logs
      - ./Images/nginx/nginx_qiita.conf:/qiita_configuration/nginx_qiita.conf
      - server-certificates:/qiita_certificates
    networks:
      - qiita-net

  qtp-biom:
    image: local-qtp-biom:latest
    command: ['./start_qtp-biom.sh']
    # network_mode: host
    # stdin_open: true
    # tty: true
    restart: no
    volumes:
      - qiita-data:/qiita
      - ./Images/qiita/config_qiita_oidc.cfg:/qiita_configurations/qiita_server.cfg:r  # TODO: do we really want to expose server settings to the plugin?
    environment:
      # TODO: is there a more elegant way to obtain this path?
      - REQUESTS_CA_BUNDLE=/opt/conda/envs/qtp-biom/lib/python3.8/site-packages/certifi/cacert.pem
      - SSL_CERT_FILE=/opt/conda/envs/qtp-biom/lib/python3.8/site-packages/certifi/cacert.pem
      - QIITA_CLIENT_DEBUG_LEVEL=DEBUG
    #depends_on:
    #- qiita
    networks:
      - qiita-net

  qtp-sequencing:
    image: local-qtp-sequencing:latest
    command: ['./start_qtp-sequencing.sh']
    # network_mode: host
    # stdin_open: true
    # tty: true
    restart: no
    volumes:
      - qiita-data:/qiita
      - ./Images/qiita/config_qiita_oidc.cfg:/qiita_configurations/qiita_server.cfg:r  # TODO: do we really want to expose server settings to the plugin?
    environment:
      # TODO: is there a more elegant way to obtain this path?
      - REQUESTS_CA_BUNDLE=/opt/conda/envs/qtp-sequencing/lib/python3.9/site-packages/certifi/cacert.pem
      - SSL_CERT_FILE=/opt/conda/envs/qtp-sequencing/lib/python3.9/site-packages/certifi/cacert.pem
      - QIITA_CLIENT_DEBUG_LEVEL=DEBUG
    #depends_on:
    #- qiita
    networks:
      - qiita-net

  qp-target-gene:
    image: local-qp-target-gene:latest
    command: ['./start_qp-target-gene.sh']
    # network_mode: host
    # stdin_open: true
    # tty: true
    restart: no
    volumes:
      - qiita-data:/qiita
      - ./Images/qiita/config_qiita_oidc.cfg:/qiita_configurations/qiita_server.cfg:r  # TODO: do we really want to expose server settings to the plugin?
    environment:
      # TODO: is there a more elegant way to obtain this path?
      - REQUESTS_CA_BUNDLE=/opt/conda/envs/qp-target-gene/lib/python2.7/site-packages/certifi/cacert.pem
      - SSL_CERT_FILE=/opt/conda/envs/qp-target-gene/lib/python2.7/site-packages/certifi/cacert.pem
      - QIITA_CLIENT_DEBUG_LEVEL=DEBUG
    #depends_on:
    #- qiita
    networks:
      - qiita-net

  qtp-visualization:
    image: local-qtp-visualization:latest
    command: ['./start_qtp-visualization.sh']
    # network_mode: host
    # stdin_open: true
    # tty: true
    restart: no
    volumes:
      - qiita-data:/qiita
      - ./Images/qiita/config_qiita_oidc.cfg:/qiita_configurations/qiita_server.cfg:r  # TODO: do we really want to expose server settings to the plugin?
    environment:
      # TODO: is there a more elegant way to obtain this path?
      - REQUESTS_CA_BUNDLE=/opt/conda/envs/qtp-visualization/lib/python3.6/site-packages/certifi/cacert.pem
      - SSL_CERT_FILE=/opt/conda/envs/qtp-visualization/lib/python3.6/site-packages/certifi/cacert.pem
      - QIITA_CLIENT_DEBUG_LEVEL=DEBUG
    #depends_on:
    #- qiita
    networks:
      - qiita-net

  qtp-diversity:
    image: local-qtp-diversity:latest
    command: ['./start_qtp-diversity.sh']
    # network_mode: host
    # stdin_open: true
    # tty: true
    restart: no
    volumes:
      - qiita-data:/qiita
      - ./Images/qiita/config_qiita_oidc.cfg:/qiita_configurations/qiita_server.cfg:r  # TODO: do we really want to expose server settings to the plugin?
    environment:
      # TODO: is there a more elegant way to obtain this path?
      - REQUESTS_CA_BUNDLE=/opt/conda/envs/qiime2/lib/python3.8/site-packages/certifi/cacert.pem
      - SSL_CERT_FILE=/opt/conda/envs/qiime2/lib/python3.8/site-packages/certifi/cacert.pem
      - QIITA_CLIENT_DEBUG_LEVEL=DEBUG
    #depends_on:
    #- qiita
    networks:
      - qiita-net

  qp-deblur:
    image: local-qp-deblur:latest
    command: ['./start_qp-deblur.sh']
    # network_mode: host
    # stdin_open: true
    # tty: true
    restart: no
    volumes:
      - qiita-data:/qiita
      - ./Images/qiita/config_qiita_oidc.cfg:/qiita_configurations/qiita_server.cfg:r  # TODO: do we really want to expose server settings to the plugin?
    environment:
      # TODO: is there a more elegant way to obtain this path?
      - REQUESTS_CA_BUNDLE=/opt/conda/envs/deblur/lib/python3.5/site-packages/certifi/cacert.pem
      - SSL_CERT_FILE=/opt/conda/envs/deblur/lib/python3.5/site-packages/certifi/cacert.pem
      - QIITA_CLIENT_DEBUG_LEVEL=DEBUG
    #depends_on:
    #- qiita
    networks:
      - qiita-net

  plugin-collector:
    # prior to qiita (master and worker) start up, iterates through the QIITA_PLUGINS : separated list of plugin containers
    # to compile all q*.conf files from plugin containers in the server-plugin-configs volume
    image: local-plugin_collector
    restart: no
    networks:
      - qiita-net
    volumes:
      - ./Images/qiita/config_qiita_oidc.cfg:/qiita_configurations/qiita_server.cfg:r
      - server-plugin-configs:/qiita_plugins
      - qiita-data:/qiita
      - server-certificates:/qiita_certificates
      #- /Daten/Git/jlab/qiita-container-anna/Images/plugin_collector/collect_configs.py:/collect.py
      #- /Daten/Git/jlab/qiita-container-anna/Images/plugin_collector/fix_test_db.py:/fix_test_db.py
    depends_on:
      - qtp-biom  # one of the plugins
      - qtp-sequencing
      - qp-target-gene
      - qtp-visualization
      - qtp-diversity
      - qp-deblur
      - qiita-db  # as values in qiita DB might be updated
    environment:
      - QIITA_PLUGINS="qtp-biom:qtp-sequencing:qp-target-gene:qtp-visualization:qtp-diversity:qp-deblur:"
    command: ['/startup_plugin_collector.sh']

networks:
  qiita-net:
    name: qiita-net
    #external: true


volumes:
  postgres-data:
    name: qiita-postgres-data
  #~ keycloak-postgres-data:
    #~ name: keycloak-postgres-data
  qiita-data:
    name: qiita-data
  server-plugin-configs: # a shared directory on qiita server side (master and workers) to collect qiita plugin configuration files
  server-certificates: # server one copy of qiita server (master and workers) certificate files. If not in volume, "plugin_collector" should copy them there
