services:
  qiita-db:
    image: postgres:15
    container_name: qiita-db
    hostname: qiita-db
    network_mode: host
    restart: no
    env_file:
      - ./environments/qiita_db.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - './environments/qiita-db-init.sh:/docker-entrypoint-initdb.d/qiita-db-init.sh'
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - "5433:5433"
    command: -p 5433

  qiita:
      image: qiita:latest 
      command: ['./start_qiita.sh'] # executes bash script inside the container
      # entrypoint: /bin/bash
      stdin_open: true
      tty: true
      network_mode: host
      ports:
        # - "21174:21174"  # wihtout nginx
        - 8383:8383
      restart: no
      depends_on:
        - qiita-db
        - nginx
      env_file:
        - './environments/qiita.env'
      environment:
        - QIITA_ROOTCA_CERT=/qiita/qiita_core/support_files/ci_rootca.crt
        - QIITA_CONFIG_FP=/config_qiita_oidc.cfg
      volumes:
          - qiita-data:/qiita
          - logs:/qiita_logs


  keycloak_web: # from https://stackoverflow.com/questions/78071458/keycloak-docker-compose
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 9999
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 9999:8080

  keycloakdb:
    image: postgres:15
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  
  nginx:
    image: nginx_qiita:latest
    ports:
      - "8383:8383"
    command: ['./start_nginx.sh']
    network_mode: host
    stdin_open: true
    tty: true
    restart: no
    volumes:
      - qiita-data:/qiita
      - logs:/qiita_logs
      

volumes:
  postgres-data:
    name: qiita-postgres-data
  keycloak-postgres-data:
    name: keycloak-postgres-data
  qiita-data:
    name: qiita-data
  logs:
    name: logs
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./qiita_logs
  
