services:
  qiita-db:
    image: postgres:15
    container_name: qiita-db
    hostname: qiita-db
    restart: no
    env_file:
      - ./environments/qiita_db.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - './environments/qiita-db-init.sh:/docker-entrypoint-initdb.d/qiita-db-init.sh'
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - qiita-net

  qiita:
      image: local-qiita:latest 
      build: # image wird hier direkt gebaut
        context: ./Images/qiita
        dockerfile: Dockerfile
      command: ['./start_qiita.sh'] # executes bash script inside the container
      # entrypoint: /bin/bash
      # stdin_open: true
      # tty: true
      # ports:
        # - "21174:21174"  # wihtout nginx
        # - 127.0.0.1:8383:8383 #damit bur ich dran komme
      restart: no
      depends_on:
        - qiita-db
        - redis
      env_file:
        - './environments/qiita.env'
      environment:
        - QIITA_ROOTCA_CERT=/qiita/qiita_core/support_files/ci_rootca.crt
        - QIITA_CONFIG_FP=/config_qiita_oidc.cfg
      volumes:
        - qiita-data:/qiita
        - ./qiita_logs:/qiita_logs
        - ./Images/qiita/config_qiita_oidc.cfg:/qiita/config_qiita_oidc.cfg
        # - ./Images/qiita/start_qiita.sh:/qiita/start_qiita.sh
      networks:
        - qiita-net
      # deploy:
      #   replicas: 3
  qiita_worker:
      image: local-qiita:latest 
      build: # image wird hier direkt gebaut
        context: ./Images/qiita
        dockerfile: Dockerfile
      command: ['./start_qiita_worker.sh'] # executes bash script inside the container
      # entrypoint: /bin/bash
      # stdin_open: true
      # tty: true
      # ports:
        # - "21174:21174"  # wihtout nginx
        # - 127.0.0.1:8383:8383 #damit bur ich dran komme
      restart: no
      depends_on:
        - qiita-db
        - redis
        - qiita
      env_file:
        - './environments/qiita.env'
      environment:
        - QIITA_ROOTCA_CERT=/qiita/qiita_core/support_files/ci_rootca.crt
        - QIITA_CONFIG_FP=/config_qiita_oidc.cfg
      volumes:
        - qiita-data:/qiita
        - ./qiita_logs:/qiita_logs
        - ./Images/qiita/config_qiita_oidc.cfg:/qiita/config_qiita_oidc.cfg
        # - ./Images/qiita/start_qiita_worker.sh:/qiita/start_qiita_worker.sh
      networks:
        - qiita-net
      deploy:
        replicas: 3
  redis:
    image: redis:latest
    restart: no
    command: >
      sh -c "redis-server --port 7777 &&
             redis-server --port 6379"
    volumes: 
      - qiita-data:/qiita
      - ./qiita_logs:/qiita_logs
    networks:
      - qiita-net
  keycloak: # from https://stackoverflow.com/questions/78071458/keycloak-docker-compose
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 9999
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev", "--http-port=9999"]
    depends_on:
      - keycloakdb
    ports:
      - 127.0.0.1:9999:9999
    networks:
      - qiita-net

  keycloakdb:
    image: postgres:15
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - qiita-net
  
  nginx:
    image: local-nginx_qiita:latest
    build:
      context: ./Images/nginx
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
    command: ['./start_nginx.sh']
    # stdin_open: true
    # tty: true
    restart: no
    depends_on:
      - qiita
    volumes:
      - qiita-data:/qiita
      - ./nginx_logs:/qiita_logs
      - ./Images/nginx/nginx_qiita.conf:/nginx_qiita.conf
    networks:
      - qiita-net
  
  qtp-biom:
    image: qtp-biom:latest
    command: ['./start_qtp-biom.sh']
    network_mode: host
    stdin_open: true
    tty: true
    restart: no
    volumes:
      - qiita-data:/qiita
    depends_on:
    - qiita
    - qiita-db

networks:
  qiita-net:
    name: qiita-net

 
volumes:
  postgres-data:
    name: qiita-postgres-data
  keycloak-postgres-data:
    name: keycloak-postgres-data
  qiita-data:
    name: qiita-data
  
