version: '3'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    hostname: keycloak-db
    restart: unless-stopped
    env_file:
      - ./environments/db.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - KEYCLOAK_DB_NAME=keycloak
      - KEYCLOAK_DB_USER=keycloak
    volumes:
      - './environments/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh'
      - 'postgres-data:/var/lib/postgresql/data'

  keycloak:
      image: quay.io/keycloak/keycloak:24.0.2
      command: ['start']
      ports:
        - "8282:8282"  # as the HAproxy of BCF if configured to forward requests here
      restart: unless-stopped
      depends_on:
        - keycloak-db
      env_file:
        - './environments/keycloak.env'
      environment:
        - KEYCLOAK_ADMIN=admin
        - KC_DB=postgres
        - KC_DB_URL_HOST=keycloak-db
        - KC_DB_URL_PORT=5432
        - KC_DB_URL_DATABASE=keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_SCHEMA=public
        - KC_HTTP_HOST=0.0.0.0
        - KC_HTTP_ENABLED=false
        - KC_HTTP_PORT=8282
        - KC_PROXY=edge
        - KC_PROXY_HEADERS=forwarded
        - KC_PROXY_ADDRESS_FORWARDING=true
        - KC_HOSTNAME_URL=https://keycloak.jlab.bio
        - KC_HOSTNAME_ADMIN_URL=https://keycloak.jlab.bio
        - KC_LOG_LEVEL=WARN
        #- KC_HOSTNAME_DEBUG=true
        #- JAVA_OPTS_APPEND="-Djava.net.preferIPv4Stack=true"

volumes:
  postgres-data:
    name: keycloak-postgres-data
