#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "$POSTGRES_DB" <<-EOSQL
	    CREATE USER "$KEYCLOAK_DB_USER" WITH password '$KEYCLOAK_DB_PASS';
	    CREATE DATABASE "$KEYCLOAK_DB_NAME";
      ALTER DATABASE "$KEYCLOAK_DB_NAME" OWNER TO "$KEYCLOAK_DB_USER"
EOSQL
