authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = PREFIXqiita-1
DNS.3 = PREFIXqiita-worker-1
DNS.4 = PREFIXqiita-worker-2
DNS.5 = PREFIXqiita-worker-3
DNS.6 = PREFIXnginx-1
