[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = DE
ST = Hesse
L = Giessen
O = JLU
OU = Stefan Janssen
CN = localhost

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = localhost
IP.1 = 127.0.0.1
DNS.2 = qiita-container-anna-qiita-1
DNS.3 = qiita-container-anna-qiita-worker-1
DNS.4 = qiita-container-anna-qiita-worker-2
DNS.5 = qiita-container-anna-qiita-worker-3
DNS.6 = qiita-container-anna-nginx-1