authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = tinqiita-nginx-1
DNS.3 = keycloak.local
DNS.4 = keycloak
DNS.5 = qiita.local
