authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = tinqiita-qiita-1
DNS.3 = tinqiita-qiita-worker-1
DNS.4 = tinqiita-qiita-worker-2
DNS.5 = tinqiita-qiita-worker-3
DNS.6 = tinqiita-nginx-1
